package com.mieai.qqbot.runtime.supervisor
enum class BotRuntimeState { DISABLED, STARTING, DISCOVERING, CONNECTING, AUTHENTICATING, ONLINE, RECONNECTING, STOPPING, STOPPED, FAILED; fun isRunning() = this in setOf(STARTING,DISCOVERING,CONNECTING,AUTHENTICATING,ONLINE,RECONNECTING) }
